import turtle
a=turtle.Turtle()
a.dot(20, "red")
b=turtle.Turtle()
b.pencolor("blue")  
c=turtle.Turtle()
c.pencolor("black") 
d=turtle.Turtle()
d.pencolor("yellow") 
e=turtle.Turtle()
e.pencolor("green")  
f=turtle.Turtle()
f.pencolor("hotpink")  
g=turtle.Turtle()
g.pencolor("purple")      
def move(t,ps,x,y):
    t.pensize(ps)
    t.shape("circle")
    t.penup()
    t.goto(x,y)
    t.pendown()
move(b,2,30,30) 
move(c,2,60,60)
move(d,2,90,90)   
move(e,2,120,120)
move(f,2,150,150)
move(g,2,180,180)
for h in range(200):
    for i in range(120):    
        b.right(1)
        b.forward(1.5)
        c.right(1)
        c.forward(2)
        d.right(1)
        d.forward(2.5)
        e.right(1)
        e.forward(3)
        f.right(1)
        f.forward(3.5)
        g.right(1)
        g.forward(4.5)
    for i in range(60):
        b.right(1)
        b.forward(1)
        c.right(1)
        c.forward(1.5)
        d.right(1)
        d.forward(2)
        e.right(1)
        e.forward(2.5)
        f.right(1)
        f.forward(3)
        g.right(1)
        g.forward(3.5)       

